# Generated by Django 5.1 on 2024-08-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tako', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangojobexecution',
            name='returncode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='djangojobexecution',
            name='stderr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djangojobexecution',
            name='stdout',
            field=models.TextField(blank=True, null=True),
        ),
    ]
