# Generated by Django 5.1 on 2024-08-31 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tako', '0002_djangojobexecution_returncode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=64)),
                ('version', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tako_script_version',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('script_args', models.TextField(blank=True, null=True)),
                ('trigger_type', models.CharField(choices=[('date', 'date'), ('interval', 'interval'), ('cron', 'cron')], max_length=16, null=True)),
                ('trigger_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tako.djangojob')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tako.scriptversion')),
            ],
            options={
                'db_table': 'tako_task',
            },
        ),
    ]
