# Generated by Django 5.1 on 2024-08-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tako', '0003_scriptversion_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptversion',
            name='filename',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='trigger_type',
            field=models.CharField(blank=True, choices=[('cron', 'cron'), ('interval', 'interval'), ('date', 'date')], db_index=True, max_length=16, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='scriptversion',
            unique_together={('filename', 'version')},
        ),
    ]
